---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-server-olddep
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
    groups:
      - docker-hosts
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  # To test the upgrade process without breaking the idempotence check
  # - install omero during the prepare step which is only run once
  # - attempt to upgrade in the converge step
  playbooks:
    prepare: ../resources/install-oldomero.yml
    converge: ../resources/upgrade-omero.yml
  inventory:
    host_vars:
      omero-server-olddep:
        omero_server_ice_version: "3.6"
        omero_server_release: present
        postgresql_version: "9.4"
    group_vars:
      docker-hosts:
        omero_server_systemd_require_network: false
scenario:
  name: olddep
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
