---
- name: Install OMERO 5.2 on both old and new servers
  hosts: all

  roles:

    - role: ome.postgresql
      postgresql_install_server: true
      postgresql_databases:
        - name: omero
      postgresql_users:
        - user: omero
          password: omero
          databases: [omero]

    - role: ansible-role-omero-server
      omero_server_system_managedrepo_group: importer
      omero_server_config_set:
        Ice.IPv6: "0"
        omero.client.ui.tree.type_order:
          - screen
          - plate
          - project
          - dataset
      # This will override host_vars (this is checked by the later tasks)
      omero_server_release: "5.2"
      omero_server_python3: false

  tasks:

    - name: get OMERO version
      become: true
      become_user: omero-server
      command: /opt/omero/server/OMERO.server/bin/omero version
      register: oldomero_version

    - name: check that OMERO 5.2 was installed
      assert:
        that:
          - oldomero_version.stdout.startswith('5.2.8-')

    - name: additional config file
      copy:
        content: >
          config set omero.policy.binary_access -- "-read,-write,-image,-plate"
        dest: /opt/omero/server/config/molecule-additional-config.omero
      notify:
        - restart omero-server
